[package]
name = "infinitas-arena-client"
version = "1.1.1"
edition = "2021"
build = "build.rs"

[lib]
name = "infinitas_arena_client_lib"
crate-type = ["rlib"]

[dependencies]
notify = "6.1.1"
rfd = "0.15.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-deep-link = "2"
tauri-plugin-single-instance = { version = "2", features = ["deep-link"] }
tauri-plugin-tts = "0.1.2"
tauri-plugin-updater = "2.5.1"
unicode-normalization = "0.1"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }

[build-dependencies]
tauri-build = { version = "2", features = [] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
