export const MATCHMAKING_INITIAL_RATING_RANGE = 50;
export const MATCHMAKING_RATING_RANGE_STEP = 50;
export const MATCHMAKING_RATING_RANGE_STEP_SECONDS = 30;
export const MATCHMAKING_RATING_RANGE_MAX = 300;
export const MATCHMAKING_ARENA_MIN_PLAYERS = 2;
export const MATCHMAKING_ARENA_MAX_PLAYERS = 4;
export const MATCHMAKING_ARENA_PARTIAL_START_SECONDS = 90;
