export const READY_CHECK_TTL_MINUTES = 20;
export const START_MIN_PLAYERS = 2;
export const PICKING_TTL_SECONDS = 120;
export const BPL4_PICKING_TTL_SECONDS = 180;

export const ROUND_SOFT_TTL_SECONDS = 300;
export const HOST_SKIP_UNLOCK_SECONDS = 240;
export const ROUND_MUSIC_SELECT_SECONDS = 45;
export const ROUND_STAGE_COUNTDOWN_AT_SECONDS = 35;
export const ROUND_START_CALL_AT_SECONDS = 52;
export const ROUND_PLAY_BEGIN_AT_SECONDS = 55;

export const MATCH_TTL_MINUTES = 30;
export const AUTO_REMATCH_RESULT_SECONDS = 20;

export const REJOIN_COOLDOWN_SECONDS = 40;

export const PING_INTERVAL_SECONDS = 20;
export const PING_TIMEOUT_MISSES = 2;
