export const READY_CHECK_TTL_MINUTES = 20;
export const START_MIN_PLAYERS = 2;
export const PICKING_TTL_SECONDS = 120;

export const ROUND_SOFT_TTL_SECONDS = 300;
export const HOST_SKIP_UNLOCK_SECONDS = 240;
export const ROUND_MUSIC_SELECT_SECONDS = 60;
export const ROUND_STAGE_COUNTDOWN_AT_SECONDS = 50;
export const ROUND_START_CALL_AT_SECONDS = 72;
export const ROUND_PLAY_BEGIN_AT_SECONDS = 75;

export const MATCH_TTL_MINUTES = 30;

export const REJOIN_COOLDOWN_SECONDS = 10;
