"""initial schema

Revision ID: 56de8b2e92e1
Revises: 
Create Date: 2025-07-21 19:24:40.919362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '56de8b2e92e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    conn.execute(text("DROP TABLE IF EXISTS song_result"))
    conn.execute(text("DROP TABLE IF EXISTS user"))
    conn.execute(text("DROP TABLE IF EXISTS song"))
    conn.execute(text("DROP TABLE IF EXISTS room"))
    conn.execute(text("DROP TABLE IF EXISTS db_version"))
    
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('room_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_pass', sa.Text(), nullable=False),
    sa.Column('mode', sa.Integer(), nullable=False),
    sa.Column('user_num', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('song',
    sa.Column('song_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('stage_no', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('song_name', sa.Text(), nullable=False),
    sa.Column('play_style', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Text(), nullable=False),
    sa.Column('notes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('song_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_token', sa.Text(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('song_result',
    sa.Column('song_result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('result_token', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('miss_count', sa.Integer(), nullable=False),
    sa.Column('lamp', sa.Text(), nullable=False),
    sa.Column('rank', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.song_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('song_result_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song_result')
    op.drop_table('user')
    op.drop_table('song')
    op.drop_table('room')
    # ### end Alembic commands ###
