name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'  # v1.0.0 などタグがpushされたらトリガー
  release:
    types: [created]  # リリース作成時にも実行したい場合に有効

jobs:
  build:
    runs-on: windows-latest
    environment: 
      name: production
    env:
      PYTHONIOENCODING: utf-8

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run build_release.py
        run: |
          python build_release.py

      - name: Decode Self-Signed Certificate
        shell: pwsh
        run: |
          $bytes = [System.Convert]::FromBase64String($Env:CODESIGN_PFX)
          [IO.File]::WriteAllBytes("codesign_test.pfx", $bytes)

      - name: Sign EXE with Self-Signed Cert
        shell: pwsh
        run: |
          $certFile = "codesign_test.pfx"
          $certPass = $Env:CODESIGN_PASSWORD
          $timestampUrl = "http://timestamp.digicert.com"
          $exePath = "dist/INFINITAS_Online_Battle/INFINITAS_Online_Battle.exe"

          $args = @(
            "sign",
            "/f", $certFile,
            "/p", $certPass,
            "/tr", $timestampUrl,
            "/td", "sha256",
            "/fd", "sha256",
            $exePath
          )

          & "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\signtool.exe" @args

      - name: Archive build artifacts
        run: |
          powershell Compress-Archive -Path dist/INFINITAS_Online_Battle/* -DestinationPath dist/INFINITAS_Online_Battle.zip

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: dist/INFINITAS_Online_Battle.zip
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}