name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'  # v1.0.0 などタグがpushされたらトリガー
  release:
    types: [created]  # リリース作成時にも実行したい場合に有効

jobs:
  build:
    runs-on: windows-latest
    environment: 
      name: production
    env:
      PYTHONIOENCODING: utf-8

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run build_release.py
        run: |
          python build_release.py

      - name: Code sign EXE and DLLs
        uses: skymatic/code-sign-action@v1
        with:
          certificate: '${{ secrets.CODESIGN_PFX }}'
          password: '${{ secrets.CODESIGN_PASSWORD }}'
          certificatesha1: '${{ secrets.CERTHASH }}'
          certificatename: '${{ secrets.CERTNAME }}'
          description: 'INFINITAS Online Battle'
          timestampUrl: 'http://timestamp.digicert.com'
          folder: 'dist/INFINITAS_Online_Battle'
          recursive: true

      - name: Archive build artifacts
        run: |
          powershell Compress-Archive -Path dist/INFINITAS_Online_Battle/* -DestinationPath dist/INFINITAS_Online_Battle.zip

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: dist/INFINITAS_Online_Battle.zip
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}